version: "2"
services:
  proxy:
    build: ./pyproxy
    ports:
    - "3000:8000"
    env_file:
      - ./erasure.env
    # volumes:
    #  - ./pyproxy:/usr/local/src/pyproxy

  redis:
    image: redis:3.2.8

  coder:
    build: ./pycoder
    environment:
      - sec_measure=confd
    env_file:
      - ./erasure.env
    # volumes:
    #  - ./pycoder:/usr/local/src/app
  zoo1:
    image: zookeeper
    restart: always
    ports:
      - 2181:2181
    environment:
      - ZOO_MY_ID=1