version: "3"
services:
  proxy:
    build: ./pyproxy
    ports:
      - "3000:8000"
    env_file:
      - ./erasure.env
    deploy:
      mode: replicated
      placement:
        constraints: [node.role == manager]

  coder:
    build: ./pycoder
    environment:
      - sec_measure=confd
    env_file:
      - ./erasure.env
    deploy:
      mode: replicated
      placement:
        constraints: [node.role == manager]

  zoo1:
    image: zookeeper
    restart: always
    ports:
      - 2181:2181
    environment:
      - ZOO_MY_ID=1
    deploy:
      mode: replicated
      placement:
        constraints: [node.role == manager]

  metadata:
    image: redis:3.2.8
    deploy:
      mode: replicated
      placement:
        constraints: [node.role == manager]

  redis:
    image: redis:3.2.8
    deploy:
      mode: replicated
      placement:
        constraints: [node.role == worker]