proxy:
  build: ./py-proxy
  ports:
  - "3000:8000"
  links:
  - redis
  - coder
  env_file:
    - ./erasure.env

redis:
  image: redis

coder:
  build: ./pycoder
  environment:
    - sec_measure=confd
    - splitter=ec
    - k=10
    - m=4
  env_file:
    - ./erasure.env
