version: "2"
services:
  proxy:
    container_name: proxy
    hostname: proxy
    build: ./pyproxy
    ports:
    - "3000:8000"
    env_file:
      - ./erasure.env
    # volumes:
    #  - ./pyproxy:/usr/local/src/pyproxy

  redis:
    container_name: redis
    image: redis:3.2.8

  coder:
    container_name: coder
    hostname: coder
    build: ./pycoder
    environment:
      - sec_measure=confd
      - splitter=ec
      - k=10
      - m=4
      - type=jerasure_rs_cauchy
    env_file:
      - ./erasure.env
    # volumes:
    #  - ./pycoder:/usr/local/src/app
